config/routes.rb
Rails.application.routes.draw do

  resources :cocktails, only: [:new, :create, :destroy, :show, :index] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy] # because the exercice wants it that way
  resources :ingredients, only: [:index, :show, :new, :create, :destroy]

  root 'cocktails#index'

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :ingredients, through: :doses
  has_many :doses, :dependent => :destroy


  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :ingredient, presence: true
  validates :cocktail, presence: true
  validates :ingredient_id, uniqueness: { scope: :cocktail_id}
  # that works too => validates :cocktail_id, uniqueness: { scope: :ingredient_id}
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

protected

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = @cocktail.doses.build(dose_params)
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  protected

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController


  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.create(ingredient_params)
    redirect_to @ingredient
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
    redirect_to ingredients_path
  end

protected

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>
<%= link_to 'create cocktail', new_cocktail_path %> | <%= link_to 'create ingredient', new_ingredient_path %>
<hr>
<% @cocktails.each do |cocktail| %>
<p><%= cocktail.name %> | <%= link_to 'show', cocktail_path(cocktail) %></p>
<% end %>

app/views/cocktails/new.html.erb
<h1>Add new cocktail</h1>
<hr>
<%= form_for @cocktail do |f| %>



  <% if @cocktail.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @cocktail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>
<hr>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<%= link_to 'show cocktails', cocktails_path %> | <%= link_to 'add doses', new_cocktail_dose_path(@cocktail) %>
<hr>
<% @cocktail.doses.each do |dose| %>
<p> <%= dose.description %> <%= link_to('delete', dose_path(dose), method: :delete) %></p>
<% end %>

app/views/doses/new.html.erb
<h1>Add dose</h1>
<hr>
<%= form_for [@cocktail, @dose] do |f| %>


  <% if @dose.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @dose.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.select :ingredient_id, @ingredients.collect {|i| [ i.name, i.id ] } %>
  <%= f.submit "submit" %>
<% end %>
<hr>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>
<%= link_to 'create an ingredient', new_ingredient_path %> | <%= link_to 'show cocktails', cocktails_path %>
<hr>
<% @ingredients.each do |ingredient| %>
<p><%= ingredient.name %> | <%= link_to('delete', ingredient_path(ingredient), method: :delete) %></p>
<% end %>

app/views/ingredients/new.html.erb
<h1>Create an ingredient</h1>
<hr>
<%= form_for @ingredient do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>
<p><%= link_to "Back", ingredients_path %></p>

app/views/ingredients/show.html.erb
<h1>Ingredient</h1>
<hr>
<p><%= @ingredient.name %></p>
<%= link_to 'back to list of ingredients', ingredients_path %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MisterCocktail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>